--[[ KING PERFORMANCE | MOONSEC V3 OBFUSCATION | AUTHORIZED: ZAYAN ]]
local _0xK,_0xZ=game:GetService("StarterGui"),{'\73\110\105\116\105\97\108\105\122\105\110\103\32\75\105\110\103\32\86\51','\66\121\112\97\115\115\105\110\103\32\72\97\110\100\115\104\97\107\101','\76\111\97\100\105\110\103\32\77\97\116\104\32\77\111\100\117\108\101\115','\68\101\99\114\121\112\116\105\110\103\32\68\97\116\97','\65\117\116\104\111\114\105\122\101\100\58\32\122\97\121\97\110'}for i,v in ipairs(_0xZ)do local h=""for _=1,12 do h=h..string.format("%X",math.random(0,15))end print("["..h.."] "..v)_0xK:SetCore("SendNotification",{Title="🛡️ SECURITY",Text=v,Duration=1})task.wait(0.2)end
local Fluent=loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))()
local W=Fluent:CreateWindow({Title="All Hub | All Game Script",SubTitle="by zayan",TabWidth=160,Size=UDim2.fromOffset(580,460),Acrylic=false,Theme="Dark",MinimizeKey=Enum.KeyCode.LeftControl})
local G=Instance.new("ScreenGui",game.CoreGui)local B=Instance.new("TextButton",G)local C=Instance.new("UICorner",B)B.Name="HUB"B.BackgroundColor3=Color3.fromRGB(30,30,30)B.Position=UDim2.new(0.12,0,0.15,0)B.Size=UDim2.new(0,50,0,50)B.Text="HUB"B.TextColor3=Color3.fromRGB(255,255,255)B.Draggable=true B.Active=true C.CornerRadius=UDim.new(0,12)B.MouseButton1Click:Connect(function()W:Minimize()end)
local T={M=W:AddTab({Title="Security",Icon="shield"}),S=W:AddTab({Title="Sailor piece script",Icon="anchor"}),R=W:AddTab({Title="Rivals",Icon="crosshair"}),F=W:AddTab({Title="Fisch",Icon="waves"}),K=W:AddTab({Title="King Legacy",Icon="crown"}),B=W:AddTab({Title="Blox Fruit",Icon="apple"}),G=W:AddTab({Title="Grow a Garden",Icon="leaf"}),T=W:AddTab({Title="Tsunami",Icon="waves"}),ST=W:AddTab({Title="Settings",Icon="settings"})}
T.M:AddButton({Title="Infinite Yield",Callback=function()loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()end})
T.S:AddButton({Title="Chiyo Hub",Callback=function()loadstring(game:HttpGet('https://raw.githubusercontent.com/kaisenlmao/loader/refs/heads/main/chiyo.lua'))()end})
T.S:AddButton({Title="Kite Hub",Callback=function()loadstring(game:HttpGet('https://raw.githubusercontent.com/GoblinKun009/Script/refs/heads/main/KiteLoader'))()end})
T.S:AddButton({Title="Void Hub",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/VoidDeveloper67/Void-Hub/refs/heads/main/VoidHub.lua"))()end})
T.S:AddButton({Title="Express Hub",Callback=function()loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/d8824b23a4d9f2e0d62b4e69397d206b.lua"))()end})
T.R:AddButton({Title="Rivals Main",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Nexoo2/Verified/refs/heads/main/Rivals.Loader"))()end})
T.F:AddButton({Title="GoombaHub",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/JustLevel/goombahub/main/fisch.lua"))()end})
T.K:AddButton({Title="Zee Hub",Callback=function()loadstring(game:HttpGet('https://zuwz.me/Ls-Zee-Hub-KL'))()end})
T.K:AddButton({Title="Omg Hub",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Omgshit/Scripts/main/MainLoader.lua"))()end})
T.B:AddButton({Title="Gravity Hub",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Dev-GravityHub/BloxFruit/refs/heads/main/Main.lua"))()end})
T.G:AddButton({Title="Speed Hub",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua",true))()end})
T.T:AddButton({Title="NEOX HUB",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/hassanxzayn-lua/NEOXHUBMAIN/refs/heads/main/loader",true))()end})
T.ST:AddSlider("WS",{Title="Walkspeed",Default=16,Min=16,Max=500,Rounding=1,Callback=function(v)game.Players.LocalPlayer.Character.Humanoid.WalkSpeed=v end})
W:SelectTab(1)
